[build]
  command = "npm run build"  # Adjust this based on your build setup (e.g., npm, yarn)
  publish = "build"          # Adjust this based on your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
